namespace Bunit;

/// <summary>
/// Represents WAI-ARIA roles used to identify the type of an element.
/// Mirrors Playwright.NET's AriaRole enum for familiarity.
/// </summary>
public enum AriaRole
{
	Alert,
	AlertDialog,
	Application,
	Article,
	Banner,
	Blockquote,
	Button,
	Caption,
	Cell,
	Checkbox,
	Code,
	ColumnHeader,
	Combobox,
	Complementary,
	ContentInfo,
	Definition,
	Deletion,
	Dialog,
	Directory,
	Document,
	Emphasis,
	Feed,
	Figure,
	Form,
	Generic,
	Grid,
	GridCell,
	Group,
	Heading,
	Img,
	Insertion,
	Link,
	List,
	Listbox,
	Listitem,
	Log,
	Main,
	Mark,
	Marquee,
	Math,
	Menu,
	Menubar,
	Menuitem,
	Menuitemcheckbox,
	Menuitemradio,
	Meter,
	Navigation,
	None,
	Note,
	Option,
	Paragraph,
	Presentation,
	Progressbar,
	Radio,
	Radiogroup,
	Region,
	Row,
	Rowgroup,
	Rowheader,
	Scrollbar,
	Search,
	Searchbox,
	Separator,
	Slider,
	Spinbutton,
	Status,
	Strong,
	Subscript,
	Superscript,
	Switch,
	Tab,
	Table,
	Tablist,
	Tabpanel,
	Term,
	Textbox,
	Time,
	Timer,
	Toolbar,
	Tooltip,
	Tree,
	Treegrid,
	Treeitem,
}

internal static class AriaRoleExtensions
{
	internal static string ToRoleString(this AriaRole role) => role switch
	{
		AriaRole.Alert => "alert",
		AriaRole.AlertDialog => "alertdialog",
		AriaRole.Application => "application",
		AriaRole.Article => "article",
		AriaRole.Banner => "banner",
		AriaRole.Blockquote => "blockquote",
		AriaRole.Button => "button",
		AriaRole.Caption => "caption",
		AriaRole.Cell => "cell",
		AriaRole.Checkbox => "checkbox",
		AriaRole.Code => "code",
		AriaRole.ColumnHeader => "columnheader",
		AriaRole.Combobox => "combobox",
		AriaRole.Complementary => "complementary",
		AriaRole.ContentInfo => "contentinfo",
		AriaRole.Definition => "definition",
		AriaRole.Deletion => "deletion",
		AriaRole.Dialog => "dialog",
		AriaRole.Directory => "directory",
		AriaRole.Document => "document",
		AriaRole.Emphasis => "emphasis",
		AriaRole.Feed => "feed",
		AriaRole.Figure => "figure",
		AriaRole.Form => "form",
		AriaRole.Generic => "generic",
		AriaRole.Grid => "grid",
		AriaRole.GridCell => "gridcell",
		AriaRole.Group => "group",
		AriaRole.Heading => "heading",
		AriaRole.Img => "img",
		AriaRole.Insertion => "insertion",
		AriaRole.Link => "link",
		AriaRole.List => "list",
		AriaRole.Listbox => "listbox",
		AriaRole.Listitem => "listitem",
		AriaRole.Log => "log",
		AriaRole.Main => "main",
		AriaRole.Mark => "mark",
		AriaRole.Marquee => "marquee",
		AriaRole.Math => "math",
		AriaRole.Menu => "menu",
		AriaRole.Menubar => "menubar",
		AriaRole.Menuitem => "menuitem",
		AriaRole.Menuitemcheckbox => "menuitemcheckbox",
		AriaRole.Menuitemradio => "menuitemradio",
		AriaRole.Meter => "meter",
		AriaRole.Navigation => "navigation",
		AriaRole.None => "none",
		AriaRole.Note => "note",
		AriaRole.Option => "option",
		AriaRole.Paragraph => "paragraph",
		AriaRole.Presentation => "presentation",
		AriaRole.Progressbar => "progressbar",
		AriaRole.Radio => "radio",
		AriaRole.Radiogroup => "radiogroup",
		AriaRole.Region => "region",
		AriaRole.Row => "row",
		AriaRole.Rowgroup => "rowgroup",
		AriaRole.Rowheader => "rowheader",
		AriaRole.Scrollbar => "scrollbar",
		AriaRole.Search => "search",
		AriaRole.Searchbox => "searchbox",
		AriaRole.Separator => "separator",
		AriaRole.Slider => "slider",
		AriaRole.Spinbutton => "spinbutton",
		AriaRole.Status => "status",
		AriaRole.Strong => "strong",
		AriaRole.Subscript => "subscript",
		AriaRole.Superscript => "superscript",
		AriaRole.Switch => "switch",
		AriaRole.Tab => "tab",
		AriaRole.Table => "table",
		AriaRole.Tablist => "tablist",
		AriaRole.Tabpanel => "tabpanel",
		AriaRole.Term => "term",
		AriaRole.Textbox => "textbox",
		AriaRole.Time => "time",
		AriaRole.Timer => "timer",
		AriaRole.Toolbar => "toolbar",
		AriaRole.Tooltip => "tooltip",
		AriaRole.Tree => "tree",
		AriaRole.Treegrid => "treegrid",
		AriaRole.Treeitem => "treeitem",
		_ => throw new ArgumentOutOfRangeException(nameof(role), role, $"Unknown AriaRole value: {role}"),
	};
}
