namespace Bunit.Web.Stubs;

internal static class HeaderProvider
{
	public const string Header = """
	                             // <auto-generated>
	                             //   This code was generated by bunit.generators.
	                             //   Changes to this file may cause incorrect behavior and will be lost if
	                             //   the code is regenerated.
	                             // </auto-generated>
	                             #nullable enable
	                             """;
}
