namespace Bunit.Rendering;

/// <summary>
/// The half-open range <c>[Start, End)</c> a component occupies in the
/// markup generated for the root component of its render tree.
/// </summary>
internal readonly record struct ComponentMarkupRange(int ComponentId, int Start, int End)
{
	public bool Contains(int index) => index >= Start && index < End;
}

/// <summary>
/// The markup generated by the <see cref="Htmlizer"/> and the range of it each component rendered.
/// </summary>
internal sealed record HtmlizerResult(string Markup, IReadOnlyList<ComponentMarkupRange> Ranges);
