name: TEST

on:
  create: [tags]

env:
  VERSION: ${GITHUB_REF/refs\/tags\/v/}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo $VERSION
